### PR TITLE
Add target directory to .gitignore

### PR DESCRIPTION
**Pull request by c71n93**
Added `target` directory to `.gitignore`.

### CODE REVIEW

**Comment by c71n93** [comment]
@yegor256 take a look please

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by c71n93** [comment]
@rultor status

**Comment by c71n93** [comment]
@yegor256 rultor still can't merge. Maybe lines:
```
architect:
  - yegor256
```
need to be added to `.rultor.yml` so you can ask rultor to merge?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by c71n93** [comment]
@yegor256 I know what the problem is. There is no prolog installed. So line:
```
sudo apt-get install swi-prolog
```
need to be added to `.rultor.yml` to `install:`.

**Comment by c71n93** [comment]
@yegor256 could you please fix [this](https://github.com/objectionary/aoi2/pull/11#issuecomment-1434687319)?

**Comment by yegor256** [comment]
@rultor merge

**Comment by c71n93** [comment]
@yegor256 I'm sorry, I forgot about `-y`option to autoconfirm. Could you please correct this string:
```
sudo apt-get install -y swi-prolog
```

**Comment by yegor256** [comment]
@rultor merge

**Comment by c71n93** [comment]
@yegor256 [this](https://github.com/objectionary/aoi2/pull/11#issuecomment-1435667983) error caused by `qulice` plugin. I just add `LICENCE.txt` and it fixed it. But then, `qulice` throws an error with dependencies, that I described here: #12. So now I will try to solve this dependency issue.

**Comment by c71n93** [comment]
@yegor256 I have fixed all issues. Now it should be able to merge. Do I understand correctly that if is no longer `architect` in `.rulrot.yml`, then I can also try @rultor merge?

**Comment by c71n93** [comment]
@rultor merge

**Comment by c71n93** [comment]
@yegor256 could you please merge this?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
