### PR TITLE
Partially document code

### LINKED ISSUE #19: Document the code
Code need to be fully or partially documented.

### PR DESCRIPTION
**Pull request by c71n93**
Closes #19. Documented only classes, which are involved in the generation of the Prolog file. Classes, that interact with `xmir` files, such as `PrologInteractor` and `FileTransformer` should be rewritten.

### CODE REVIEW

**Comment by yegor256** [comment]
@mximp please, check this one

**Comment by mximp** [comment]
@c71n93 Please check [this blog post](https://www.yegor256.com/2015/03/09/objects-end-with-er.html). I believe the whole OO design of the classes here should be redesigned. It's better to have "real world" entities (with names as meaningful nouns) which have clear interfaces. As an example of first step, `PlGenerator` seems to be `PrologScrirpt` which encapsulates destination for a script:
```
class PrologScript {
    private Path destination;

    fun get() {
        // logic to generate the script content
    }
}
```

**Comment by c71n93** [comment]
> @c71n93 Please check [this blog post](https://www.yegor256.com/2015/03/09/objects-end-with-er.html). I believe the whole OO design of the classes here should be redesigned. It's better to have "real world" entities (with names as meaningful nouns) which have clear interfaces. As an example of first step, `PlGenerator` seems to be `PrologScrirpt` which encapsulates destination for a script:
> 
> ```
> class PrologScript {
>     private Path destination;
> 
>     fun get() {
>         // logic to generate the script content
>     }
> }
> ```
> 
> It's probably the subject of next PR

@mximp I agree, that all code need redesign. But I think it should be done gradually, in the process of closing other issues.

In this PR, I decided not to refactor the code, because it don't have enough tests. Without unit tests, something may break during refactoring.

**Review by mximp — APPROVED** [review]

**Comment by c71n93** [comment]
@yegor256 could you merge please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
